In [1]:
import scanpy as sc
import anndata
import numpy as np
from scipy.sparse import csr_matrix

In [3]:
ATAC_h5ad_path = '/home/wsg/BM/data/HSPC/RNA+ATAC/p10/float/HSPC-multiome-p10-ATAC-peaks.h5ad'
RNA_h5ad_path = '/home/wsg/BM/data/HSPC/RNA+ATAC/p10/float/HSPC-multiome-p10-RNA-counts.h5ad'

RNA_data = sc.read_h5ad(RNA_h5ad_path)
ATAC_data = sc.read_h5ad(ATAC_h5ad_path)

In [6]:
RNA_data

AnnData object with n_obs × n_vars = 10594 × 23418
    obs: 'day', 'donor', 'cell_type', 'technology', 'barcode'

In [18]:
raw_rna = np.round(np.expm1(RNA_data.X.copy()))

In [20]:
raw_int = csr_matrix(raw_rna.astype(int))

In [23]:
raw_int.toarray()

array([[  0,   0,   0, ...,   0, 187,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [102,   0,   0, ...,   0,   0, 102]])

In [24]:
RNA_data.X = raw_int

In [29]:
output_path = "/home/wsg/BM/data/HSPC/RNA+ATAC/p10"
# save hd5
RNA_data.write_h5ad("{}/HSPC-multiome-p10-RNA-counts.h5ad".format(output_path))

In [39]:
ATAC_data.X

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 3.7700207, 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]], dtype=float32)

In [40]:
raw_atac_binary = csr_matrix(np.where(ATAC_data.X != 0, 1, 0))

In [41]:
raw_atac_binary.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
ATAC_data.X = raw_atac_binary

In [48]:
output_path = "/home/wsg/BM/data/HSPC/RNA+ATAC/p10"
# save hd5
ATAC_data.write_h5ad("{}/HSPC-multiome-p10-ATAC-peaks.h5ad".format(output_path))

In [47]:
raw_atac_binary.shape

(10594, 228942)